# Generated by Django 3.1.2 on 2020-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplsim', '0002_auto_20201020_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
