# Generated by Django 3.1.2 on 2020-10-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplsim', '0003_auto_20201020_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbrev',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
