# Generated by Django 3.1.2 on 2020-10-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplsim', '0005_matchweek_ict_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
