# Generated by Django 3.1.2 on 2020-10-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fplsim', '0008_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
